### ISSUE TITLE
Remove all of an item in cart

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#109] opened 2017-05-24 18:59 UTC
make it possible to remove all of an item with one click from the cart view

**Comment by bglusman** [comment] 2017-10-10 03:24
To clarify, there's already this button in the ordering pane but if it's in cart and you've switched credit types, there's no way to remove from cart directly

**Comment by aaronshim** [comment] 2017-10-13 21:02
Is this being looked at? If not, could I try taking a look at it for Hacktoberfest? Thanks so much!

**Comment by bglusman** [comment] 2017-10-14 19:34
@aaronshim that would be awesome, please take a look and let me know if any questions or problems!

**Comment by fcapovilla** [comment] 2017-11-04 18:03
Is this a duplicate of issue #118? If it is, can we close this issue?

**Comment by bglusman** [comment] 2017-11-04 18:04
oh it totally is good catch... sigh...

**Closed as completed by bglusman** 2017-11-04 18:04 UTC
Labels: duplicate, enhancement, small, Hacktoberfest
